import http from "k6/http";
import { check, sleep } from "k6";
import { Counter } from "k6/metrics";

const BASE_URL = __ENV.BASE_URL || "http://localhost:8080";

const errors = new Counter("cloudforge_errors");

export const options = {
  scenarios: {
    smoke: {
      executor: "constant-vus",
      vus: 2,
      duration: "30s",
      tags: { scenario: "smoke" },
      exec: "smoke",
    },
    load: {
      executor: "ramping-vus",
      startTime: "35s",
      startVUs: 0,
      stages: [
        { duration: "1m", target: 20 },
        { duration: "2m", target: 20 },
        { duration: "1m", target: 50 },
        { duration: "2m", target: 50 },
        { duration: "30s", target: 0 },
      ],
      tags: { scenario: "load" },
      exec: "load",
    },
  },
  thresholds: {
    http_req_failed: ["rate<0.01"],
    "http_req_duration{scenario:load}": ["p(95)<300", "p(99)<800"],
    "http_req_duration{scenario:smoke}": ["p(95)<200"],
  },
};

export function smoke() {
  const res = http.get(`${BASE_URL}/livez`);
  check(res, { "livez is 200": (r) => r.status === 200 }) || errors.add(1);
  sleep(1);
}

export function load() {
  const createRes = http.post(
    `${BASE_URL}/api/v1/items`,
    JSON.stringify({ name: `k6-item-${__VU}-${__ITER}`, description: "generated by k6 load test" }),
    { headers: { "Content-Type": "application/json" } }
  );
  const created = check(createRes, {
    "create status is 201": (r) => r.status === 201,
  });
  if (!created) {
    errors.add(1);
    sleep(1);
    return;
  }

  const item = JSON.parse(createRes.body);

  const getRes = http.get(`${BASE_URL}/api/v1/items/${item.id}`);
  check(getRes, { "get status is 200": (r) => r.status === 200 }) || errors.add(1);

  const listRes = http.get(`${BASE_URL}/api/v1/items`);
  check(listRes, { "list status is 200": (r) => r.status === 200 }) || errors.add(1);

  const deleteRes = http.del(`${BASE_URL}/api/v1/items/${item.id}`);
  check(deleteRes, { "delete status is 204": (r) => r.status === 204 }) || errors.add(1);

  sleep(1);
}
